# Generated by Django 2.2.3 on 2021-04-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('useremail', models.CharField(max_length=100)),
                ('userimage', models.ImageField(upload_to='users/')),
                ('userPassword', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=50)),
            ],
        ),
    ]
