# Generated by Django 2.2.3 on 2021-04-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessmentname', models.CharField(max_length=100)),
                ('assessmentdate', models.DateField()),
                ('facilityname', models.CharField(max_length=100)),
                ('cityname', models.CharField(max_length=100)),
                ('statename', models.CharField(max_length=100)),
                ('assessment_options', models.CharField(max_length=100)),
            ],
        ),
    ]
