# Generated by Django 3.2 on 2021-04-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_auto_20210426_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('asset_gross_value', models.CharField(max_length=100)),
                ('expected_effort', models.CharField(max_length=100)),
                ('organization_name', models.CharField(max_length=100)),
                ('business_unit', models.CharField(max_length=100)),
                ('organization_type', models.CharField(max_length=100)),
                ('facilitator', models.CharField(max_length=100)),
                ('critical_service_point', models.CharField(max_length=100)),
                ('include_other_enterprise_business_units', models.CharField(max_length=100)),
            ],
        ),
    ]
